name: Docker Image CI
on:
  pull_request:
    branches: 
      - master
      - staging/*
      
jobs:
  clone-repo:
    name: Load environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./
          mode:
          load-mode: strict

  docker-ci:
    name: Build & push image
    runs-on: ubuntu-latest
    needs: clone-repo
    steps:
      - name: Docker build & publish
        uses: bitovi/github-actions-docker-publish@v1.0.7
        with:
          checkout: false
          image_tag: ${{ env.VER }}
          use_sha: false
          org_name: ${{ secrets.DOCKERHUB_ORG }}
          repo_name: printer-info-snatcher
          use_latest: true
          docker_username:  ${{ secrets.DOCKERHUB_USER }}
          docker_password: ${{ secrets.DOCKERHUB_PSW }}
          working-directory: ./
