name: Docker Image CI

on:
  push:
    branches: 
      - master
      - staging/*
  pull_request:
    branches: 
      - master
      - staging/*
  
jobs:
  docker-image-push:
    name: Build & push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./
          mode: empty
          load-mode: strict   
          
      - name: Build Image
        run: docker build . --file Dockerfile --tag printer-info-snatcher:${{ env.VER }}

    
      - name: Build and push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.VER }}
